<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon" href="{{ asset('images/logo.png') }}" type="image/x-icon">
    <title>Feeder School Report</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 15mm;
        }
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            padding: 20px;
        }
        .print-date {
            font-size: 10px;
            margin-bottom: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            width: 60px;
            height: 60px;
        }
        .header h1 {
            font-size: 14px;
            font-weight: bold;
            margin-top: 5px;
            text-transform: uppercase;
        }
        .header p {
            font-size: 10px;
        }
        .title {
            text-align: center;
            font-weight: bold;
            font-size: 12px;
            padding: 5px 0;
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px 8px;
            text-align: left;
        }
        th {
            font-weight: bold;
            font-size: 10px;
            text-transform: uppercase;
            text-align: center;
        }
        td {
            text-align: center;
        }
        td:first-child {
            text-align: left;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            border-top: 1px solid #000;
            padding-top: 10px;
        }
        @media print {
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <p class="print-date">Printed: {{ date('F d, Y') }}</p>

    <div class="header">
        <img src="{{ public_path('images/logo.png') }}" alt="Logo">
        <h1>{{ strtoupper(env('APP_NAME')) }}</h1>
        <p>School Address</p>
        <p>000-0000-000 | example@example.com</p>
    </div>

    <div class="title">FEEDER SCHOOL REPORT — {{ $selectedYear }}</div>

    <table>
        <thead>
            <tr>
                <th style="width: 40%;">School</th>
                <th style="width: 15%;">Ongoing</th>
                <th style="width: 15%;">Failed</th>
                <th style="width: 15%;">Passed</th>
                <th style="width: 15%;">Total Applicant</th>
            </tr>
        </thead>
        <tbody>
            @forelse($feederSchools as $school)
                <tr>
                    <td>{{ $school->last_school_attended }}</td>
                    <td>{{ number_format($school->ongoing) }}</td>
                    <td>{{ number_format($school->failed) }}</td>
                    <td>{{ number_format($school->passed) }}</td>
                    <td>{{ number_format($school->total_applicants) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center;">No feeder school data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report was automatically generated by the Enrollment System.</p>
        <p>© {{ date('Y') }} All Rights Reserved</p>
    </div>
</body>
</html>