<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon" href="{{ asset('images/logo.png') }}" type="image/x-icon">
    <title>{{ strtoupper(env('APP_NAME')) }} - Schedule Applicants</title>
    <style>
        @page {
            size: A4;
            margin: 15mm;
        }
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 11px;
            line-height: 1.4;
            padding: 20px;
        }
        .print-date {
            font-size: 9px;
            margin-bottom: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            width: 60px;
            height: 60px;
        }
        .header h1 {
            font-size: 14px;
            font-weight: bold;
            margin-top: 5px;
            text-transform: uppercase;
        }
        .header p {
            font-size: 10px;
        }
        .title {
            text-align: center;
            font-weight: bold;
            font-size: 12px;
            padding: 5px 0;
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            margin-bottom: 15px;
        }
        .schedule-info {
            font-size: 10px;
            margin-bottom: 15px;
            padding: 10px;
        }
        .schedule-info p {
            margin-bottom: 3px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px 8px;
            text-align: left;
        }
        th {
            font-weight: bold;
            font-size: 10px;
            text-transform: uppercase;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 9px;
            border-top: 1px solid #000;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <p class="print-date">Printed: {{ date('F d, Y') }}</p>
    
    <div class="header">
        <img src="{{ public_path('images/logo.png') }}" alt="Logo">
        <h1>{{ strtoupper(env('APP_NAME')) }}</h1>
        <p>School Address</p>
        <p>000-0000-000 | example@example.com</p>
    </div>
    
    <div class="title">SCHEDULE APPLICANTS LIST</div>
    
    <div class="schedule-info">
        <p><strong>Process Type:</strong> {{ ucfirst($schedule->process) }}</p>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($schedule->date)->format('F d, Y') }}</p>
        <p><strong>Time:</strong> {{ \Carbon\Carbon::parse($schedule->start_time)->format('h:i A') }} - {{ \Carbon\Carbon::parse($schedule->end_time)->format('h:i A') }}</p>
        <p><strong>Proctor:</strong> {{ $schedule->proctor->name ?? '' }}</p>
        <p><strong>Total Applicants:</strong> {{ $applicants->count() }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Application No.</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($applicants as $index => $applicant)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $applicant->application_no }}</td>
                <td>{{ $applicant->last_name }}, {{ $applicant->first_name }} {{ $applicant->middle_name }}</td>
                <td>{{ $applicant->email }}</td>
                <td>{{ $applicant->mobile_number }}</td>
                <td>{{ ucfirst($applicant->status) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center;">No applicants assigned to this schedule</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report was automatically generated by the Enrollment System.</p>
        <p>© {{ date('Y') }} All Rights Reserved</p>
    </div>
</body>
</html>
